import os

ELASTIC_SEARCH_HOST = os.environ['ELASTIC_SEARCH_HOST']
ELASTIC_SEARCH_USERNAME = os.environ['ELASTIC_SEARCH_USERNAME']
ELASTIC_SEARCH_PASSWORD = os.environ['ELASTIC_SEARCH_PASSWORD']
MYSQL_URL = os.environ['MYSQL_URL']
SQLALCHEMY_POOL_RECYCLE = 60
